AllCops:
  NewCops: disable
  Exclude:
    - features/**/*
    - db/**/*
    - bundle_bin/**/*
    - vendor/**/*
  Include:
    - damerau-levenshtein.gemspec
Metrics/ModuleLength:
  Max: 1000
Style/StringLiterals:
  EnforcedStyle: double_quotes
Layout/DotPosition:
  EnforcedStyle: trailing
Naming/FileName:
  Enabled: false
